package database

import (
	"cosmetics_catalog/models"
)

func SeedTestData() error {
	// 1. Бренды
	brands := []models.Brand{
		{Name: "Bioderma", Slug: "bioderma"},
		{Name: "L'Oréal Paris", Slug: "loreal-paris"},
		{Name: "Pusy", Slug: "pusy"},
		{Name: "Dior", Slug: "dior"},
		{Name: "Dr. Jart+", Slug: "dr-jart"},
		{Name: "Clarins", Slug: "clarins"},
		{Name: "Catrice", Slug: "catrice"},
		{Name: "Clinique", Slug: "clinique"},
		{Name: "Shiseido", Slug: "shiseido"},
		{Name: "Kiko Milano", Slug: "kiko-milano"},
		{Name: "Erborian", Slug: "erborian"},
	}
	for _, brand := range brands {
		if err := DB.Create(&brand).Error; err != nil {
			return err
		}
	}

	// 2. Категории с подкатегориями
	categories := []models.Category{
		{
			Name: "Макияж",
			Slug: "makiyazh",
			Subcategories: []models.Subcategory{
				{Name: "Лицо", Slug: "litso"},
				{Name: "Глаза", Slug: "glaza"},
				{Name: "Губы", Slug: "guby"},
			},
		},
		{
			Name: "Уход",
			Slug: "ukhod",
			Subcategories: []models.Subcategory{
				{Name: "Очищение", Slug: "ochishenie"},
				{Name: "Увлажнение", Slug: "uvlazhnenie"},
				{Name: "Тонизирование", Slug: "tonizirovanie"},
			},
		},
	}
	for _, category := range categories {
		if err := DB.Create(&category).Error; err != nil {
			return err
		}
	}

	// 3. Получение нужных подкатегорий из БД
	var (
		makeupFace, makeupEyes, makeupLips       models.Subcategory
		careCleansing, careHydration, careToning models.Subcategory
	)
	subMap := map[string]*models.Subcategory{
		"Лицо":          &makeupFace,
		"Глаза":         &makeupEyes,
		"Губы":          &makeupLips,
		"Очищение":      &careCleansing,
		"Увлажнение":    &careHydration,
		"Тонизирование": &careToning,
	}
	for name, ptr := range subMap {
		if err := DB.Where("name = ?", name).First(ptr).Error; err != nil {
			return err
		}
	}

	// 4. Продукты
	products := []models.Product{
		// bioderma
		{
			Name:          "Гель для умывания Sensibio Foaming Gel",
			Slug:          "bioderma-sensibio-foaming-gel",
			BrandID:       1,
			SubcategoryID: careCleansing.ID,
			Price:         1450.00,
			ImagePath:     "images/bioderma/sensibio-foaming-gel.jpg",
			Description:   "Мягкий пенящийся гель для чувствительной кожи",
			IsOnSale:      false,
		},
		{
			Name:          "Мицеллярная вода Sensibio H2O",
			Slug:          "bioderma-sensibio-h2o",
			BrandID:       1,
			SubcategoryID: careCleansing.ID,
			Price:         1290.00,
			ImagePath:     "images/bioderma/sensibio-h2o.jpg",
			Description:   "Легендарная мицеллярная вода для чувствительной кожи",
			IsOnSale:      true,
			SalePrice:     1099.00,
		},
		{
			Name:          "Гель-пенка для умывания Sébium Gel Moussant",
			Slug:          "bioderma-sebium-gel-moussant",
			BrandID:       1,
			SubcategoryID: careCleansing.ID,
			Price:         1350.00,
			ImagePath:     "images/bioderma/sebium-gel-moussant.jpg",
			Description:   "Очищающий гель для проблемной кожи с цинком",
			IsOnSale:      false,
		},
		{
			Name:          "Очищающий крем Atoderm Intensive Gel",
			Slug:          "bioderma-atoderm-intensive-gel",
			BrandID:       1,
			SubcategoryID: careCleansing.ID,
			Price:         1650.00,
			ImagePath:     "images/bioderma/atoderm-intensive-gel.jpg",
			Description:   "Нежный гель для сухой и атопичной кожи",
			IsOnSale:      true,
			SalePrice:     1399.00,
		},
		{
			Name:          "Увлажняющий крем Hydrabio Gel-Crème",
			Slug:          "bioderma-hydrabio-gel-creme",
			BrandID:       1,
			SubcategoryID: careHydration.ID,
			Price:         1890.00,
			ImagePath:     "images/bioderma/hydrabio-gel-creme.jpg",
			Description:   "Легкий гель-крем для обезвоженной кожи",
			IsOnSale:      false,
		},
		{
			Name:          "Патчи для контура глаз Hydrabio Patch",
			Slug:          "bioderma-hydrabio-patch",
			BrandID:       1,
			SubcategoryID: careHydration.ID,
			Price:         1250.00,
			ImagePath:     "images/bioderma/hydrabio-patch.jpg",
			Description:   "Экспресс-уход для области вокруг глаз",
			IsOnSale:      true,
			SalePrice:     999.00,
		},
		{
			Name:          "BB крем Sébium 30 SPF",
			Slug:          "bioderma-sebium-bb-cream",
			BrandID:       1,
			SubcategoryID: makeupFace.ID,
			Price:         2100.00,
			ImagePath:     "images/bioderma/sebium-bb-cream.jpg",
			Description:   "Тональное средство с матирующим эффектом",
			IsOnSale:      false,
		},
		{
			Name:          "Минеральная пудра Mineral Powder",
			Slug:          "bioderma-mineral-powder",
			BrandID:       1,
			SubcategoryID: makeupFace.ID,
			Price:         1750.00,
			ImagePath:     "images/bioderma/mineral-powder.jpg",
			Description:   "Рассыпчатая пудра для чувствительной кожи",
			IsOnSale:      true,
			SalePrice:     1490.00,
		},
		{
			Name:          "Тушь для ресниц Volume Mascara",
			Slug:          "bioderma-volume-mascara",
			BrandID:       1,
			SubcategoryID: makeupEyes.ID,
			Price:         1650.00,
			ImagePath:     "images/bioderma/volume-mascara.jpg",
			Description:   "Тушь с эффектом объема для чувствительных глаз",
			IsOnSale:      false,
		},
		{
			Name:          "Карандаш для глаз Sensibio Eye Pencil",
			Slug:          "bioderma-sensibio-eye-pencil",
			BrandID:       1,
			SubcategoryID: makeupEyes.ID,
			Price:         950.00,
			ImagePath:     "images/bioderma/sensibio-eye-pencil.jpg",
			Description:   "Мягкий карандаш для чувствительных глаз",
			IsOnSale:      true,
			SalePrice:     799.00,
		},
		{
			Name:          "Бальзам для губ Atoderm Lip Stick",
			Slug:          "bioderma-atoderm-lip-stick",
			BrandID:       1,
			SubcategoryID: makeupLips.ID,
			Price:         890.00,
			ImagePath:     "images/bioderma/atoderm-lip-stick.jpg",
			Description:   "Восстанавливающий бальзам для сухих губ",
			IsOnSale:      false,
		},
		{
			Name:          "Тональный бальзам для губ Sensibio Lip",
			Slug:          "bioderma-sensibio-lip",
			BrandID:       1,
			SubcategoryID: makeupLips.ID,
			Price:         1200.00,
			ImagePath:     "images/bioderma/sensibio-lip.jpg",
			Description:   "Уходовый бальзам с легким тонирующим эффектом",
			IsOnSale:      true,
			SalePrice:     990.00,
		},
		// L'Oréal Paris
		{
			Name:          "Тональный крем True Match",
			Slug:          "loreal-true-match",
			BrandID:       2,
			SubcategoryID: makeupFace.ID,
			Price:         899.00,
			ImagePath:     "images/loreal/true-match.jpg",
			Description:   "Тональный крем с естественным покрытием",
			IsOnSale:      false,
		},
		{
			Name:          "Тушь для ресниц Lash Paradise",
			Slug:          "loreal-lash-paradise",
			BrandID:       2,
			SubcategoryID: makeupEyes.ID,
			Price:         799.00,
			ImagePath:     "images/loreal/lash-paradise.jpg",
			Description:   "Объемная тушь для эффекта накладных ресниц",
			IsOnSale:      true,
			SalePrice:     699.00,
		},
		{
			Name:          "Тональный крем Infallible 24H Fresh Wear",
			Slug:          "loreal-infallible-24h-fresh",
			BrandID:       2, // ID бренда L'Oréal Paris
			SubcategoryID: makeupFace.ID,
			Price:         1299.00,
			ImagePath:     "images/loreal/infallible-24h-fresh.jpg",
			Description:   "Стойкий тональный крем с эффектом свежести на 24 часа",
			IsOnSale:      false,
		},
		{
			Name:          "Консилер Infallible More Than Concealer",
			Slug:          "loreal-infallible-concealer",
			BrandID:       2,
			SubcategoryID: makeupFace.ID,
			Price:         899.00,
			ImagePath:     "images/loreal/infallible-concealer.jpg",
			Description:   "Высокопокрывающий консилер с матовым финишем",
			IsOnSale:      true,
			SalePrice:     749.00,
		},
		{
			Name:          "Тени для век Color Riche Monos",
			Slug:          "loreal-color-riche-monos",
			BrandID:       2,
			SubcategoryID: makeupEyes.ID,
			Price:         599.00,
			ImagePath:     "images/loreal/color-riche-monos.jpg",
			Description:   "Кремовые тени с эффектом влажного сияния",
			IsOnSale:      false,
		},
		{
			Name:          "Подводка для глаз Superliner",
			Slug:          "loreal-superliner",
			BrandID:       2,
			SubcategoryID: makeupEyes.ID,
			Price:         699.00,
			ImagePath:     "images/loreal/superliner.jpg",
			Description:   "Стойкая подводка с тонким аппликатором",
			IsOnSale:      true,
			SalePrice:     599.00,
		},
		{
			Name:          "Жидкая помада Rouge Signature",
			Slug:          "loreal-rouge-signature",
			BrandID:       2,
			SubcategoryID: makeupLips.ID,
			Price:         899.00,
			ImagePath:     "images/loreal/rouge-signature.jpg",
			Description:   "Легкая стойкая помада с эффектом поцелуя",
			IsOnSale:      false,
		},
		{
			Name:          "Блеск для губ Glow Paradise",
			Slug:          "loreal-glow-paradise",
			BrandID:       2,
			SubcategoryID: makeupLips.ID,
			Price:         799.00,
			ImagePath:     "images/loreal/glow-paradise.jpg",
			Description:   "Бальзам-блеск с уходовыми маслами",
			IsOnSale:      true,
			SalePrice:     699.00,
		},
		{
			Name:          "Мицеллярная вода для чувствительной кожи",
			Slug:          "loreal-micellar-sensitive",
			BrandID:       2,
			SubcategoryID: careCleansing.ID,
			Price:         599.00,
			ImagePath:     "images/loreal/micellar-sensitive.jpg",
			Description:   "Безспиртовая формула для чувствительной кожи",
			IsOnSale:      false,
		},
		{
			Name:          "Гель для умывания Чистая кожа",
			Slug:          "loreal-pure-clay-gel",
			BrandID:       2,
			SubcategoryID: careCleansing.ID,
			Price:         499.00,
			ImagePath:     "images/loreal/pure-clay-gel.jpg",
			Description:   "Очищающий гель с глиной для проблемной кожи",
			IsOnSale:      true,
			SalePrice:     399.00,
		},
		// Pusy
		{
			Name:          "Тональная основа Skin Like",
			Slug:          "pusy-skin-like-foundation",
			BrandID:       3, // ID бренда Pusy
			SubcategoryID: makeupFace.ID,
			Price:         1890.00,
			ImagePath:     "images/pusy/skin-like-foundation.jpg",
			Description:   "Легкая тональная основа с эффектом второй кожи",
			IsOnSale:      false,
		},
		{
			Name:          "Консилер Perfect Cover",
			Slug:          "pusy-perfect-cover-concealer",
			BrandID:       3,
			SubcategoryID: makeupFace.ID,
			Price:         990.00,
			ImagePath:     "images/pusy/perfect-cover-concealer.jpg",
			Description:   "Высокопокрывающий консилер с кремовой текстурой",
			IsOnSale:      true,
			SalePrice:     790.00,
		},
		{
			Name:          "Палетка теней Nude Fantasy",
			Slug:          "pusy-nude-fantasy-palette",
			BrandID:       3,
			SubcategoryID: makeupEyes.ID,
			Price:         1590.00,
			ImagePath:     "images/pusy/nude-fantasy-palette.jpg",
			Description:   "Палетка из 12 nude-оттенков с разными текстурами",
			IsOnSale:      false,
		},
		{
			Name:          "Тушь Volume Queen",
			Slug:          "pusy-volume-queen-mascara",
			BrandID:       3,
			SubcategoryID: makeupEyes.ID,
			Price:         890.00,
			ImagePath:     "images/pusy/volume-queen-mascara.jpg",
			Description:   "Тушь для эффекта объемных ресниц",
			IsOnSale:      true,
			SalePrice:     690.00,
		},
		{
			Name:          "Жидкая матовая помада Velvet Touch",
			Slug:          "pusy-velvet-touch-lipstick",
			BrandID:       3,
			SubcategoryID: makeupLips.ID,
			Price:         1190.00,
			ImagePath:     "images/pusy/velvet-touch-lipstick.jpg",
			Description:   "Стойкая матовая помада с комфортной текстурой",
			IsOnSale:      false,
		},
		{
			Name:          "Блеск для губ Glass Shine",
			Slug:          "pusy-glass-shine-gloss",
			BrandID:       3,
			SubcategoryID: makeupLips.ID,
			Price:         790.00,
			ImagePath:     "images/pusy/glass-shine-gloss.jpg",
			Description:   "Блеск с эффектом стеклянных губ",
			IsOnSale:      true,
			SalePrice:     590.00,
		},
		{
			Name:          "Мицеллярная вода 3-в-1",
			Slug:          "pusy-3in1-micellar",
			BrandID:       3,
			SubcategoryID: careCleansing.ID,
			Price:         890.00,
			ImagePath:     "images/pusy/3in1-micellar.jpg",
			Description:   "Удаляет макияж, очищает и тонизирует кожу",
			IsOnSale:      false,
		},
		{
			Name:          "Гель для умывания Pure Balance",
			Slug:          "pusy-pure-balance-gel",
			BrandID:       3,
			SubcategoryID: careCleansing.ID,
			Price:         690.00,
			ImagePath:     "images/pusy/pure-balance-gel.jpg",
			Description:   "Мягкий гель для нормальной и комбинированной кожи",
			IsOnSale:      true,
			SalePrice:     490.00,
		},

		// Dior
		{
			Name:          "Помада Dior Addict Lip Glow",
			Slug:          "dior-lip-glow",
			BrandID:       4,
			SubcategoryID: makeupLips.ID,
			Price:         3200.00,
			ImagePath:     "images/dior/lip-glow.jpg",
			Description:   "Бальзам для губ с эффектом сияния и уходом",
			IsOnSale:      false,
		},
		{
			Name:          "Жидкая помада Rouge Dior",
			Slug:          "dior-rouge-dior",
			BrandID:       4,
			SubcategoryID: makeupLips.ID,
			Price:         3500.00,
			ImagePath:     "images/dior/rouge-dior.jpg",
			Description:   "Стойкая кремовая текстура с 16-часовым ношением",
			IsOnSale:      true,
			SalePrice:     3100.00,
		},
		{
			Name:          "Карандаш для губ Contour Lipliner",
			Slug:          "dior-lipliner",
			BrandID:       4,
			SubcategoryID: makeupLips.ID,
			Price:         2500.00,
			ImagePath:     "images/dior/lipliner.jpg",
			Description:   "Мягкий карандаш для контура губ",
			IsOnSale:      false,
		},
		{
			Name:          "Тушь Diorshow Pump'N'Volume",
			Slug:          "dior-pump-volume",
			BrandID:       4,
			SubcategoryID: makeupEyes.ID,
			Price:         2900.00,
			ImagePath:     "images/dior/pump-volume.jpg",
			Description:   "Тушь для объема с инновационной щеточкой",
			IsOnSale:      false,
		},
		{
			Name:          "Палетка теней Backstage",
			Slug:          "dior-backstage-palette",
			BrandID:       4,
			SubcategoryID: makeupEyes.ID,
			Price:         4500.00,
			ImagePath:     "images/dior/backstage-palette.jpg",
			Description:   "Профессиональная палетка с 9 оттенками",
			IsOnSale:      true,
			SalePrice:     4000.00,
		},
		{
			Name:          "Подводка для глаз On Stage",
			Slug:          "dior-on-stage",
			BrandID:       4,
			SubcategoryID: makeupEyes.ID,
			Price:         2700.00,
			ImagePath:     "images/dior/on-stage.jpg",
			Description:   "Стойкая подводка с тонким аппликатором",
			IsOnSale:      false,
		},
		{
			Name:          "Тональный крем Forever Skin Glow",
			Slug:          "dior-forever-glow",
			BrandID:       4,
			SubcategoryID: makeupFace.ID,
			Price:         4800.00,
			ImagePath:     "images/dior/forever-glow.jpg",
			Description:   "Тональное средство с эффектом сияния",
			IsOnSale:      false,
		},
		{
			Name:          "Хайлайтер DiorGlow",
			Slug:          "dior-glow-highlighter",
			BrandID:       4,
			SubcategoryID: makeupFace.ID,
			Price:         3800.00,
			ImagePath:     "images/dior/glow-highlighter.jpg",
			Description:   "Хайлайтер для сияющего эффекта",
			IsOnSale:      true,
			SalePrice:     3400.00,
		},
		{
			Name:          "Мицеллярная вода Capture Totale",
			Slug:          "dior-capture-totale",
			BrandID:       4,
			SubcategoryID: careCleansing.ID,
			Price:         3800.00,
			ImagePath:     "images/dior/capture-totale.jpg",
			Description:   "Деликатное очищение с розовой водой",
			IsOnSale:      false,
		},
		{
			Name:          "Крем для век Capture Youth",
			Slug:          "dior-capture-youth",
			BrandID:       4,
			SubcategoryID: careHydration.ID,
			Price:         5200.00,
			ImagePath:     "images/dior/capture-youth.jpg",
			Description:   "Антивозрастной уход для области вокруг глаз",
			IsOnSale:      true,
			SalePrice:     4700.00,
		},

		// Dr. Jart+
		{
			Name:          "BB-крем Premium Beauty Balm",
			Slug:          "drjart-bb-cream",
			BrandID:       5, // ID бренда Dr. Jart+
			SubcategoryID: makeupFace.ID,
			Price:         2800.00,
			ImagePath:     "images/drjart/bb-cream.jpg",
			Description:   "Многофункциональный BB-крем с SPF40 и уходом",
			IsOnSale:      false,
		},
		{
			Name:          "CC-крем Cicapair Tiger Grass Color Correcting",
			Slug:          "drjart-cc-cream",
			BrandID:       5,
			SubcategoryID: makeupFace.ID,
			Price:         3200.00,
			ImagePath:     "images/drjart/cc-cream.jpg",
			Description:   "Корректирующий крем с противовоспалительным эффектом",
			IsOnSale:      true,
			SalePrice:     2900.00,
		},
		{
			Name:          "Кушон Ceramidin Cream-Cushion",
			Slug:          "drjart-ceramidin-cushion",
			BrandID:       5,
			SubcategoryID: makeupFace.ID,
			Price:         3500.00,
			ImagePath:     "images/drjart/ceramidin-cushion.jpg",
			Description:   "Тональное средство с церамидами для сухой кожи",
			IsOnSale:      false,
		},
		{
			Name:          "Крем Ceramidin Cream",
			Slug:          "drjart-ceramidin-cream",
			BrandID:       5,
			SubcategoryID: careHydration.ID,
			Price:         4200.00,
			ImagePath:     "images/drjart/ceramidin-cream.jpg",
			Description:   "Интенсивное увлажнение с керамидным комплексом",
			IsOnSale:      false,
		},
		{
			Name:          "Сыворотка Cicapair Tiger Grass Serum",
			Slug:          "drjart-cicapair-serum",
			BrandID:       5,
			SubcategoryID: careHydration.ID,
			Price:         3800.00,
			ImagePath:     "images/drjart/cicapair-serum.jpg",
			Description:   "Успокаивающая сыворотка для чувствительной кожи",
			IsOnSale:      true,
			SalePrice:     3400.00,
		},
		{
			Name:          "Маска Rubber Lover Vital Hydra Solution",
			Slug:          "drjart-hydra-mask",
			BrandID:       5,
			SubcategoryID: careHydration.ID,
			Price:         1200.00,
			ImagePath:     "images/drjart/hydra-mask.jpg",
			Description:   "Гидрофильная маска для интенсивного увлажнения",
			IsOnSale:      false,
		},
		{
			Name:          "Гель для умывания Dermaclear Micro Foam",
			Slug:          "drjart-micro-foam",
			BrandID:       5,
			SubcategoryID: careCleansing.ID,
			Price:         1800.00,
			ImagePath:     "images/drjart/micro-foam.jpg",
			Description:   "Мягкая пенка с микрочастицами для глубокого очищения",
			IsOnSale:      false,
		},
		{
			Name:          "Мицеллярная вода Dermaclear Microwater",
			Slug:          "drjart-microwater",
			BrandID:       5,
			SubcategoryID: careCleansing.ID,
			Price:         2200.00,
			ImagePath:     "images/drjart/microwater.jpg",
			Description:   "Деликатное очищение без необходимости смывания",
			IsOnSale:      true,
			SalePrice:     1900.00,
		},
		{
			Name:          "Патчи для глаз Hydro Jet Eye Patch",
			Slug:          "drjart-eye-patch",
			BrandID:       5,
			SubcategoryID: careHydration.CategoryID,
			Price:         2500.00,
			ImagePath:     "images/drjart/eye-patch.jpg",
			Description:   "Гидрогелевые патчи для мгновенного свежего взгляда",
			IsOnSale:      false,
		},
		{
			Name:          "Крем Cicapair Tiger Grass Cream",
			Slug:          "drjart-tiger-grass",
			BrandID:       5,
			SubcategoryID: careHydration.ID,
			Price:         3600.00,
			ImagePath:     "images/drjart/tiger-grass.jpg",
			Description:   "Восстанавливающий крем с тигровой травой",
			IsOnSale:      true,
			SalePrice:     3200.00,
		},
		// Clarins
		{
			Name:          "Everlasting Cushion Foundation",
			Slug:          "clarins-cushion-foundation",
			BrandID:       6,
			SubcategoryID: makeupFace.ID,
			Price:         4900.00,
			ImagePath:     "images/clarins/cushion-foundation.jpg",
			Description:   "Кушон с эффектом естественного сияния",
			IsOnSale:      false,
		},
		{
			Name:          "Blush Prodige Illuminating Cheek Colour",
			Slug:          "clarins-blush-prodige",
			BrandID:       6,
			SubcategoryID: makeupFace.ID,
			Price:         3200.00,
			ImagePath:     "images/clarins/blush-prodige.jpg",
			Description:   "Румяна с светоотражающими частицами",
			IsOnSale:      true,
			SalePrice:     2900.00,
		},

		// Макияж глаз
		{
			Name:          "Ombre Matte Eyeshadow",
			Slug:          "clarins-ombre-matte",
			BrandID:       6,
			SubcategoryID: makeupEyes.ID,
			Price:         2200.00,
			ImagePath:     "images/clarins/ombre-matte.jpg",
			Description:   "Матовая тень для век стойкой формулы",
			IsOnSale:      false,
		},
		{
			Name:          "Graphik Ink Liner",
			Slug:          "clarins-graphik-ink",
			BrandID:       6,
			SubcategoryID: makeupEyes.ID,
			Price:         2500.00,
			ImagePath:     "images/clarins/graphik-ink.jpg",
			Description:   "Стойкая подводка с тонким аппликатором",
			IsOnSale:      false,
		},

		// Макияж губ
		{
			Name:          "Joli Rouge Brilliant Lipstick",
			Slug:          "clarins-joli-rouge",
			BrandID:       6,
			SubcategoryID: makeupLips.ID,
			Price:         2700.00,
			ImagePath:     "images/clarins/joli-rouge.jpg",
			Description:   "Блестящая помада с увлажняющим эффектом",
			IsOnSale:      false,
		},

		// Уход - очищение
		{
			Name:          "Gentle Foaming Cleanser",
			Slug:          "clarins-foaming-cleanser",
			BrandID:       6,
			SubcategoryID: careCleansing.ID,
			Price:         2800.00,
			ImagePath:     "images/clarins/foaming-cleanser.jpg",
			Description:   "Мягкая очищающая пенка",
			IsOnSale:      true,
			SalePrice:     2500.00,
		},

		// Уход - увлажнение
		{
			Name:          "Hydra-Essentiel Silky Cream",
			Slug:          "clarins-hydra-essentiel",
			BrandID:       6,
			SubcategoryID: careHydration.ID,
			Price:         4900.00,
			ImagePath:     "images/clarins/hydra-essentiel.jpg",
			Description:   "Увлажняющий крем с шелковой текстурой",
			IsOnSale:      false,
		},

		// Уход - тонизирование
		{
			Name:          "Toning Lotion With Camomile",
			Slug:          "clarins-toning-lotion",
			BrandID:       6,
			SubcategoryID: careToning.ID,
			Price:         3100.00,
			ImagePath:     "images/clarins/toning-lotion.jpg",
			Description:   "Тонизирующий лосьон с экстрактом ромашки",
			IsOnSale:      false,
		},

		// Дополнительные продукты для категорий
		{
			Name:          "Beauty Flash Balm",
			Slug:          "clarins-flash-balm",
			BrandID:       6,
			SubcategoryID: makeupFace.ID,
			Price:         3900.00,
			ImagePath:     "images/clarins/flash-balm.jpg",
			Description:   "Бальзам для мгновенного сияния кожи",
			IsOnSale:      true,
			SalePrice:     3500.00,
		},
		{
			Name:          "Lip Comfort Oil",
			Slug:          "clarins-lip-oil",
			BrandID:       6,
			SubcategoryID: makeupLips.ID,
			Price:         2200.00,
			ImagePath:     "images/clarins/lip-oil.jpg",
			Description:   "Питательное масло для губ",
			IsOnSale:      false,
		},
		// Catrice
		{
			Name:          "HD Liquid Coverage Foundation",
			Slug:          "catrice-hd-foundation",
			BrandID:       7,
			SubcategoryID: makeupFace.ID,
			Price:         899.00,
			ImagePath:     "images/catrice/hd-foundation.jpg",
			Description:   "Тональная основа с полным покрытием",
			IsOnSale:      true,
			SalePrice:     699.00,
		},
		{
			Name:          "Prime And Fine Mattifying Powder",
			Slug:          "catrice-mattifying-powder",
			BrandID:       7,
			SubcategoryID: makeupFace.ID,
			Price:         599.00,
			ImagePath:     "images/catrice/mattifying-powder.jpg",
			Description:   "Матирующая пудра для лица",
			IsOnSale:      false,
		},

		// Макияж глаз
		{
			Name:          "Glam & Doll Mascara",
			Slug:          "catrice-glam-doll",
			BrandID:       7,
			SubcategoryID: makeupEyes.ID,
			Price:         649.00,
			ImagePath:     "images/catrice/glam-doll.jpg",
			Description:   "Тушь для объема ресниц",
			IsOnSale:      false,
		},
		{
			Name:          "Eyebrow Stylist Pencil",
			Slug:          "catrice-eyebrow-pencil",
			BrandID:       7,
			SubcategoryID: makeupEyes.ID,
			Price:         399.00,
			ImagePath:     "images/catrice/eyebrow-pencil.jpg",
			Description:   "Карандаш для бровей с щеточкой",
			IsOnSale:      true,
			SalePrice:     349.00,
		},

		// Макияж губ
		{
			Name:          "Lip Glow Lip Balm",
			Slug:          "catrice-lip-glow",
			BrandID:       7,
			SubcategoryID: makeupLips.ID,
			Price:         349.00,
			ImagePath:     "images/catrice/lip-glow.jpg",
			Description:   "Бальзам для губ с эффектом сияния",
			IsOnSale:      false,
		},

		// Уход - очищение
		{
			Name:          "Cleansing Balm",
			Slug:          "catrice-cleansing-balm",
			BrandID:       7,
			SubcategoryID: careCleansing.ID,
			Price:         599.00,
			ImagePath:     "images/catrice/cleansing-balm.jpg",
			Description:   "Бальзам для демакияжа",
			IsOnSale:      false,
		},

		// Уход - увлажнение
		{
			Name:          "Hydro Moisturizer",
			Slug:          "catrice-hydro-moisturizer",
			BrandID:       7,
			SubcategoryID: careHydration.ID,
			Price:         749.00,
			ImagePath:     "images/catrice/hydro-moisturizer.jpg",
			Description:   "Легкий увлажняющий крем",
			IsOnSale:      true,
			SalePrice:     649.00,
		},

		// Уход - тонизирование
		{
			Name:          "Refresh Toner",
			Slug:          "catrice-refresh-toner",
			BrandID:       7,
			SubcategoryID: careToning.ID,
			Price:         499.00,
			ImagePath:     "images/catrice/refresh-toner.jpg",
			Description:   "Освежающий тоник для лица",
			IsOnSale:      false,
		},

		// Дополнительные продукты
		{
			Name:          "Concealer Liquid Camouflage",
			Slug:          "catrice-liquid-camouflage",
			BrandID:       7,
			SubcategoryID: makeupFace.ID,
			Price:         449.00,
			ImagePath:     "images/catrice/liquid-camouflage.jpg",
			Description:   "Высокопокрывающий консилер",
			IsOnSale:      false,
		},
		{
			Name:          "Lip Liner Pencil",
			Slug:          "catrice-lip-liner",
			BrandID:       7,
			SubcategoryID: makeupLips.ID,
			Price:         299.00,
			ImagePath:     "images/catrice/lip-liner.jpg",
			Description:   "Карандаш для контура губ",
			IsOnSale:      true,
			SalePrice:     249.00,
		},
		// Clinique
		{
			Name:          "Even Better Makeup SPF15",
			Slug:          "clinique-even-better",
			BrandID:       8,
			SubcategoryID: makeupFace.ID,
			Price:         4200.00,
			ImagePath:     "images/clinique/even-better.jpg",
			Description:   "Тональный крем с эффектом выравнивания тона",
			IsOnSale:      false,
		},
		{
			Name:          "Beyond Perfecting Foundation",
			Slug:          "clinique-beyond-perfecting",
			BrandID:       8,
			SubcategoryID: makeupFace.ID,
			Price:         3800.00,
			ImagePath:     "images/clinique/beyond-perfecting.jpg",
			Description:   "Тональное средство 2-в-1: крем + консилер",
			IsOnSale:      true,
			SalePrice:     3400.00,
		},

		// Макияж глаз
		{
			Name:          "High Impact Mascara",
			Slug:          "clinique-high-impact",
			BrandID:       8,
			SubcategoryID: makeupEyes.ID,
			Price:         2900.00,
			ImagePath:     "images/clinique/high-impact.jpg",
			Description:   "Тушь для объема и длины ресниц",
			IsOnSale:      false,
		},
		{
			Name:          "All About Shadow Palette",
			Slug:          "clinique-shadow-palette",
			BrandID:       8,
			SubcategoryID: makeupEyes.ID,
			Price:         3500.00,
			ImagePath:     "images/clinique/shadow-palette.jpg",
			Description:   "Палетка нейтральных теней для век",
			IsOnSale:      false,
		},

		// Макияж губ
		{
			Name:          "Almost Lipstick Black Honey",
			Slug:          "clinique-black-honey",
			BrandID:       8,
			SubcategoryID: makeupLips.ID,
			Price:         2200.00,
			ImagePath:     "images/clinique/black-honey.jpg",
			Description:   "Культовая оттеночная помада",
			IsOnSale:      false,
		},

		// Уход - очищение
		{
			Name:          "Take The Day Off Cleansing Balm",
			Slug:          "clinique-cleansing-balm",
			BrandID:       8,
			SubcategoryID: careCleansing.ID,
			Price:         3200.00,
			ImagePath:     "images/clinique/cleansing-balm.jpg",
			Description:   "Бальзам для демакияжа",
			IsOnSale:      true,
			SalePrice:     2900.00,
		},

		// Уход - увлажнение
		{
			Name:          "Moisture Surge 72-Hour",
			Slug:          "clinique-moisture-surge",
			BrandID:       8,
			SubcategoryID: careHydration.ID,
			Price:         4200.00,
			ImagePath:     "images/clinique/moisture-surge.jpg",
			Description:   "Гидратирующий крем с 72-часовым действием",
			IsOnSale:      false,
		},

		// Уход - тонизирование
		{
			Name:          "Clarifying Lotion 2",
			Slug:          "clinique-clarifying-lotion",
			BrandID:       8,
			SubcategoryID: careToning.ID,
			Price:         3100.00,
			ImagePath:     "images/clinique/clarifying-lotion.jpg",
			Description:   "Тонизирующий лосьон для нормальной кожи",
			IsOnSale:      false,
		},

		// Дополнительные продукты
		{
			Name:          "Chubby Stick Cheek Colour",
			Slug:          "clinique-chubby-cheek",
			BrandID:       8,
			SubcategoryID: makeupFace.ID,
			Price:         2500.00,
			ImagePath:     "images/clinique/chubby-cheek.jpg",
			Description:   "Кремовые румяна в стике",
			IsOnSale:      true,
			SalePrice:     2200.00,
		},
		{
			Name:          "Pop Lip Colour + Primer",
			Slug:          "clinique-pop-lip",
			BrandID:       8,
			SubcategoryID: makeupLips.ID,
			Price:         1800.00,
			ImagePath:     "images/clinique/pop-lip.jpg",
			Description:   "Помада с праймером в составе",
			IsOnSale:      false,
		},
		// Shiseido
		{
			Name:          "Synchro Skin Self-Refreshing Foundation",
			Slug:          "shiseido-synchro-foundation",
			BrandID:       9,
			SubcategoryID: makeupFace.ID,
			Price:         5200.00,
			ImagePath:     "images/shiseido/synchro-foundation.jpg",
			Description:   "Тональная основа с технологией самообновления",
			IsOnSale:      false,
		},
		{
			Name:          "Minimalist WhippedPowder Blush",
			Slug:          "shiseido-whipped-blush",
			BrandID:       9,
			SubcategoryID: makeupFace.ID,
			Price:         3500.00,
			ImagePath:     "images/shiseido/whipped-blush.jpg",
			Description:   "Воздушные румяна с эффектом вуали",
			IsOnSale:      true,
			SalePrice:     3100.00,
		},

		// Макияж глаз
		{
			Name:          "MicroLiner Ink",
			Slug:          "shiseido-microliner",
			BrandID:       9,
			SubcategoryID: makeupEyes.ID,
			Price:         2800.00,
			ImagePath:     "images/shiseido/microliner.jpg",
			Description:   "Тонкая подводка с кисточкой-иглой",
			IsOnSale:      false,
		},
		{
			Name:          "ImperialLash Mascara",
			Slug:          "shiseido-imperial-lash",
			BrandID:       9,
			SubcategoryID: makeupEyes.ID,
			Price:         3900.00,
			ImagePath:     "images/shiseido/imperial-lash.jpg",
			Description:   "Тушь для создания императорских ресниц",
			IsOnSale:      false,
		},

		// Макияж губ
		{
			Name:          "VisionAiry Gel Lipstick",
			Slug:          "shiseido-visionairy-lipstick",
			BrandID:       9,
			SubcategoryID: makeupLips.ID,
			Price:         3200.00,
			ImagePath:     "images/shiseido/visionairy-lipstick.jpg",
			Description:   "Невесомая гелевая помада",
			IsOnSale:      true,
			SalePrice:     2900.00,
		},

		// Уход - очищение
		{
			Name:          "Perfect Cleansing Oil",
			Slug:          "shiseido-cleansing-oil",
			BrandID:       9,
			SubcategoryID: careCleansing.ID,
			Price:         4100.00,
			ImagePath:     "images/shiseido/cleansing-oil.jpg",
			Description:   "Масло для демакияжа с экстрактом сакуры",
			IsOnSale:      false,
		},

		// Уход - увлажнение
		{
			Name:          "Waso Clear Mega-Hydrating Cream",
			Slug:          "shiseido-waso-cream",
			BrandID:       9,
			SubcategoryID: careHydration.ID,
			Price:         2900.00,
			ImagePath:     "images/shiseido/waso-cream.jpg",
			Description:   "Увлажняющий крем с экстрактом лотоса",
			IsOnSale:      false,
		},

		// Уход - тонизирование
		{
			Name:          "Treatment Softener Enriched",
			Slug:          "shiseido-softener",
			BrandID:       9,
			SubcategoryID: careToning.ID,
			Price:         5500.00,
			ImagePath:     "images/shiseido/softener.jpg",
			Description:   "Обогащенный тоник для подготовки кожи",
			IsOnSale:      true,
			SalePrice:     4900.00,
		},

		// Дополнительные продукты
		{
			Name:          "Synchro Skin Soft Blurring Primer",
			Slug:          "shiseido-blurring-primer",
			BrandID:       9,
			SubcategoryID: makeupFace.ID,
			Price:         3800.00,
			ImagePath:     "images/shiseido/blurring-primer.jpg",
			Description:   "Праймер с эффектом мягкого блюра",
			IsOnSale:      false,
		},
		{
			Name:          "ModernMatte Powder Lipstick",
			Slug:          "shiseido-matte-lipstick",
			BrandID:       9,
			SubcategoryID: makeupLips.ID,
			Price:         3000.00,
			ImagePath:     "images/shiseido/matte-lipstick.jpg",
			Description:   "Матовая помада с пудровой текстурой",
			IsOnSale:      false,
		},
		// Kiko Milano
		{
			Name:          "Smart Fusion Foundation",
			Slug:          "kiko-smart-fusion",
			BrandID:       10,
			SubcategoryID: makeupFace.ID,
			Price:         1299.00,
			ImagePath:     "images/kiko/smart-fusion.jpg",
			Description:   "Тональная основа с умной адаптацией",
			IsOnSale:      true,
			SalePrice:     1099.00,
		},
		{
			Name:          "Blending Wave Blush",
			Slug:          "kiko-blending-blush",
			BrandID:       10,
			SubcategoryID: makeupFace.ID,
			Price:         899.00,
			ImagePath:     "images/kiko/blending-blush.jpg",
			Description:   "Румяна с волнообразным дизайном",
			IsOnSale:      false,
		},

		// Макияж глаз
		{
			Name:          "Water Eyeshadow",
			Slug:          "kiko-water-eyeshadow",
			BrandID:       10,
			SubcategoryID: makeupEyes.ID,
			Price:         599.00,
			ImagePath:     "images/kiko/water-eyeshadow.jpg",
			Description:   "Тени с эффектом мокрого сияния",
			IsOnSale:      false,
		},
		{
			Name:          "Smart Eye Pencil",
			Slug:          "kiko-smart-pencil",
			BrandID:       10,
			SubcategoryID: makeupEyes.ID,
			Price:         499.00,
			ImagePath:     "images/kiko/smart-pencil.jpg",
			Description:   "Универсальный карандаш для глаз",
			IsOnSale:      true,
			SalePrice:     399.00,
		},

		// Макияж губ
		{
			Name:          "Velvet Passion Matte Lipstick",
			Slug:          "kiko-velvet-passion",
			BrandID:       10,
			SubcategoryID: makeupLips.ID,
			Price:         799.00,
			ImagePath:     "images/kiko/velvet-passion.jpg",
			Description:   "Матовая помада с бархатной текстурой",
			IsOnSale:      false,
		},

		// Уход - очищение
		{
			Name:          "Cleansing Oil with Jojoba",
			Slug:          "kiko-cleansing-oil",
			BrandID:       10,
			SubcategoryID: careCleansing.ID,
			Price:         999.00,
			ImagePath:     "images/kiko/cleansing-oil.jpg",
			Description:   "Очищающее масло с маслом жожоба",
			IsOnSale:      false,
		},

		// Уход - увлажнение
		{
			Name:          "Hydrating Serum",
			Slug:          "kiko-hydrating-serum",
			BrandID:       10,
			SubcategoryID: careHydration.ID,
			Price:         1499.00,
			ImagePath:     "images/kiko/hydrating-serum.jpg",
			Description:   "Увлажняющая сыворотка с гиалуроновой кислотой",
			IsOnSale:      true,
			SalePrice:     1299.00,
		},

		// Уход - тонизирование
		{
			Name:          "Rose Toner",
			Slug:          "kiko-rose-toner",
			BrandID:       10,
			SubcategoryID: careToning.ID,
			Price:         799.00,
			ImagePath:     "images/kiko/rose-toner.jpg",
			Description:   "Тоник с экстрактом розы",
			IsOnSale:      false,
		},

		// Дополнительные продукты
		{
			Name:          "Skin Evolution Concealer",
			Slug:          "kiko-skin-evolution",
			BrandID:       10,
			SubcategoryID: makeupFace.ID,
			Price:         699.00,
			ImagePath:     "images/kiko/skin-evolution.jpg",
			Description:   "Консилер с уходовыми свойствами",
			IsOnSale:      false,
		},
		{
			Name:          "Jelly Stylo Lipstick",
			Slug:          "kiko-jelly-stylo",
			BrandID:       10,
			SubcategoryID: makeupLips.ID,
			Price:         599.00,
			ImagePath:     "images/kiko/jelly-stylo.jpg",
			Description:   "Помада-стик с желеобразной текстурой",
			IsOnSale:      true,
			SalePrice:     499.00,
		},
		// Erborian
		{
			Name:          "BB Cream Au Ginseng",
			Slug:          "erborian-bb-ginseng",
			BrandID:       11,
			SubcategoryID: makeupFace.ID,
			Price:         3900.00,
			ImagePath:     "images/erborian/bb-ginseng.jpg",
			Description:   "BB-крем с женьшенем для сияния кожи",
			IsOnSale:      false,
		},
		{
			Name:          "CC Cream Red Correct",
			Slug:          "erborian-cc-red-correct",
			BrandID:       11,
			SubcategoryID: makeupFace.ID,
			Price:         4200.00,
			ImagePath:     "images/erborian/cc-red-correct.jpg",
			Description:   "CC-крем с коррекцией красноты",
			IsOnSale:      true,
			SalePrice:     3800.00,
		},

		// Макияж глаз
		{
			Name:          "Super Brow Pomade",
			Slug:          "erborian-super-brow",
			BrandID:       11,
			SubcategoryID: makeupEyes.ID,
			Price:         2900.00,
			ImagePath:     "images/erborian/super-brow.jpg",
			Description:   "Помада для бровей с фиксирующим эффектом",
			IsOnSale:      false,
		},

		// Макияж губ
		{
			Name:          "Liquid Lip Color",
			Slug:          "erborian-liquid-lip",
			BrandID:       11,
			SubcategoryID: makeupLips.ID,
			Price:         3200.00,
			ImagePath:     "images/erborian/liquid-lip.jpg",
			Description:   "Жидкая помада с комфортной текстурой",
			IsOnSale:      false,
		},
		{
			Name:          "Lip Tint",
			Slug:          "erborian-lip-tint",
			BrandID:       11,
			SubcategoryID: makeupLips.ID,
			Price:         2500.00,
			ImagePath:     "images/erborian/lip-tint.jpg",
			Description:   "Тинт для губ с эффектом сияющих губ",
			IsOnSale:      true,
			SalePrice:     2200.00,
		},

		// Уход - очищение
		{
			Name:          "Solid Cleansing Oil",
			Slug:          "erborian-solid-cleansing",
			BrandID:       11,
			SubcategoryID: careCleansing.ID,
			Price:         2800.00,
			ImagePath:     "images/erborian/solid-cleansing.jpg",
			Description:   "Твердое очищающее масло-трансформер",
			IsOnSale:      false,
		},

		// Уход - увлажнение
		{
			Name:          "Yuza Double Lotion",
			Slug:          "erborian-yuza-lotion",
			BrandID:       11,
			SubcategoryID: careHydration.ID,
			Price:         3500.00,
			ImagePath:     "images/erborian/yuza-lotion.jpg",
			Description:   "Двухфазный увлажняющий лосьон с юдзу",
			IsOnSale:      false,
		},
		{
			Name:          "Bamboo Waterlock Mask",
			Slug:          "erborian-bamboo-mask",
			BrandID:       11,
			SubcategoryID: careHydration.ID,
			Price:         2900.00,
			ImagePath:     "images/erborian/bamboo-mask.jpg",
			Description:   "Увлажняющая маска с экстрактом бамбука",
			IsOnSale:      true,
			SalePrice:     2600.00,
		},

		// Уход - тонизирование
		{
			Name:          "Ginseng Milk Toner",
			Slug:          "erborian-ginseng-toner",
			BrandID:       11,
			SubcategoryID: careToning.ID,
			Price:         3100.00,
			ImagePath:     "images/erborian/ginseng-toner.jpg",
			Description:   "Молочный тоник с экстрактом женьшеня",
			IsOnSale:      false,
		},
		{
			Name:          "Perfect Glow Skin Illuminator",
			Slug:          "erborian-perfect-glow",
			BrandID:       11,
			SubcategoryID: makeupFace.ID,
			Price:         3400.00,
			ImagePath:     "images/erborian/perfect-glow.jpg",
			Description:   "Иллюминатор для сияния кожи",
			IsOnSale:      false,
		},
	}
	for _, product := range products {
		if err := DB.Create(&product).Error; err != nil {
			return err
		}
	}

	return nil
}
